LENGTH = 5

# Make
run:
	python Grammaire.py exemple.general
	python Generer.py $(LENGTH) exemple.chomsky
	python Generer.py $(LENGTH) exemple.greibach

	python Grammaire.py exemple2.general
	python Generer.py $(LENGTH) exemple2.chomsky
	python Generer.py $(LENGTH) exemple2.greibach

	python Grammaire.py exemple3.general
	python Generer.py $(LENGTH) exemple3.chomsky
	python Generer.py $(LENGTH) exemple3.greibach

